"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { toast } from "sonner"
import { ActivePayrollSection } from "./component/active-payroll-section"
import { DeletedPayrollSection } from "./component/deleted-payroll-section"
import { PayrollActionDialog, type PayrollAction, type PayrollActionValues } from "./component/payroll-action-dialog"
import { PayrollFormDialog, type PayrollFormValues } from "./component/payroll-entry-form"
import { createPayrollRun, listPayrollRuns, loadLookupOptions, markPayrollPaid, transitionPayroll } from "../operations/operations.service"
import type { PayrollRunRecord } from "../operations/operations.types"
import { HrPageHeader } from "../shared/hr-page-header"
import type { HrOption, HrPaginationMeta } from "../shared/hr.types"
import { HrWorkspaceLayout } from "../shared/hr-workspace-layout"
import { useHrWorkspace } from "../shared/use-hr-workspace"

const DEFAULT_VALUES: PayrollFormValues = { factoryId: "", payGroupId: "", frequency: "MONTHLY", runType: "REGULAR", periodStart: "", periodEnd: "", paymentDate: "", rulePackId: "__none__", currency: "BDT", sequence: 1 }
export function PayrollWorkspace({ apiUrl }: { apiUrl: string }) {
  const { organizationId, context, handleError, refreshVersion, triggerRefresh } = useHrWorkspace(apiUrl)
  const [records, setRecords] = useState<PayrollRunRecord[]>([]); const [meta, setMeta] = useState<HrPaginationMeta | null>(null); const [loading, setLoading] = useState(true); const [page, setPage] = useState(1); const [limit, setLimit] = useState(10); const [search, setSearch] = useState("")
  const [factories, setFactories] = useState<HrOption[]>([]); const [payGroups, setPayGroups] = useState<HrOption[]>([]); const [rulePacks, setRulePacks] = useState<HrOption[]>([])
  const [open, setOpen] = useState(false); const [values, setValues] = useState<PayrollFormValues>(DEFAULT_VALUES); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState("")
  const [target, setTarget] = useState<PayrollRunRecord | null>(null); const [action, setAction] = useState<PayrollAction>("calculate"); const [actionValues, setActionValues] = useState<PayrollActionValues>({ comment: "", paidStatus: "PAID" }); const [actionError, setActionError] = useState("")
  const load = useCallback(async () => { if (!organizationId) { setLoading(false); return } setLoading(true); try { const [result, lookups] = await Promise.all([listPayrollRuns(context(), page, limit, search), loadLookupOptions(context(), ["factories", "payGroups", "rulePacks"])]); setRecords(result.items); setMeta(result.meta); setFactories(lookups.factories.map((item) => ({ value: item.id, label: `${item.code ?? ""} · ${item.displayName ?? item.name ?? item.id}` }))); setPayGroups(lookups.payGroups.map((item) => ({ value: item.id, label: `${item.code ?? ""} · ${item.name ?? item.id}` }))); setRulePacks(lookups.rulePacks.filter((item) => item.reviewStatus === "APPROVED").map((item) => ({ value: item.id, label: `${item.code} · ${item.name} v${item.version}` }))) } catch (caught) { handleError(caught, "Unable to load payroll runs.") } finally { setLoading(false) } }, [context, handleError, limit, organizationId, page, search])
  useEffect(() => { const pending = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(pending) }, [load, refreshVersion])
  const submit = async () => { if (!values.factoryId || !values.payGroupId || !values.periodStart || !values.periodEnd || !values.paymentDate) { setError("Factory, pay group, period, and payment date are required."); return } setSubmitting(true); setError(""); try { await createPayrollRun(context(), { ...values, rulePackId: values.rulePackId === "__none__" ? undefined : values.rulePackId, currency: values.currency.trim().toUpperCase() }, crypto.randomUUID()); toast.success("Payroll run created successfully."); setOpen(false); setValues(DEFAULT_VALUES); triggerRefresh() } catch (caught) { setError(handleError(caught, "Unable to create the payroll run.", false)) } finally { setSubmitting(false) } }
  const runAction = async () => { if (!target) return; setSubmitting(true); setActionError(""); try { if (action === "paid") await markPayrollPaid(context(), target.id, actionValues.paidStatus); else await transitionPayroll(context(), target.id, action, { rowVersion: target.rowVersion ?? 1, comment: actionValues.comment.trim() || undefined }, action === "calculate" || action === "reverse" ? crypto.randomUUID() : undefined); toast.success(action === "calculate" ? "Payroll calculation queued." : `Payroll ${action.replaceAll("-", " ")} completed.`); setTarget(null); triggerRefresh() } catch (caught) { setActionError(handleError(caught, "Unable to transition the payroll run.", false)) } finally { setSubmitting(false) } }
  const active = useMemo(() => records.filter((item) => item.status !== "REVERSED"), [records]); const reversed = useMemo(() => records.filter((item) => item.status === "REVERSED"), [records])
  return <HrWorkspaceLayout><HrPageHeader title="Payroll Processing" description="Create, calculate, review, approve, lock, pay, and reverse payroll through a controlled audit workflow." badges={[{ label: `${meta?.total ?? records.length} total`, variant: "secondary" }, { label: `${records.filter((item) => item.status === "LOCKED").length} locked on page` }, { label: `${reversed.length} reversed on page` }]} onRefresh={triggerRefresh} onCreate={() => { setValues(DEFAULT_VALUES); setError(""); setOpen(true) }} createLabel="New payroll run" /><ActivePayrollSection data={active} meta={meta} loading={loading} search={search} page={page} limit={limit} onSearchChange={setSearch} onPageChange={setPage} onLimitChange={setLimit} onAction={(record, nextAction) => { setTarget(record); setAction(nextAction); setActionValues({ comment: "", paidStatus: record.paidStatus || "PAID" }); setActionError("") }} /><DeletedPayrollSection data={reversed} /><PayrollFormDialog open={open} values={values} factories={factories} payGroups={payGroups} rulePacks={rulePacks} submitting={submitting} error={error} onOpenChange={setOpen} onChange={(name, value) => setValues((current) => ({ ...current, [name]: value }))} onSubmit={submit} /><PayrollActionDialog open={Boolean(target)} action={action} values={actionValues} submitting={submitting} error={actionError} onOpenChange={(next) => { if (!next) setTarget(null) }} onChange={(name, value) => setActionValues((current) => ({ ...current, [name]: value }))} onSubmit={runAction} /></HrWorkspaceLayout>
}
