"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { toast } from "sonner"
import { ActiveLoansSection } from "./component/active-loans-section"
import { DeletedLoansSection } from "./component/deleted-loans-section"
import { LoanFormDialog, type LoanFormValues } from "./component/loan-form-dialog"
import { LoanStatusDialog, type LoanStatusValues } from "./component/loan-status-dialog"
import { createLoan, getReport, loadLookupOptions, updateLoanStatus } from "../operations/operations.service"
import type { LoanRecord } from "../operations/operations.types"
import { HrPageHeader } from "../shared/hr-page-header"
import type { HrOption } from "../shared/hr.types"
import { HrWorkspaceLayout } from "../shared/hr-workspace-layout"
import { useHrWorkspace } from "../shared/use-hr-workspace"

const DEFAULT_VALUES: LoanFormValues = { employeeId: "", loanNumber: "", principal: 0, installmentAmount: 0, startDate: "", remarks: "" }
export function LoanWorkspace({ apiUrl }: { apiUrl: string }) {
  const { organizationId, context, handleError, refreshVersion, triggerRefresh } = useHrWorkspace(apiUrl)
  const [records, setRecords] = useState<LoanRecord[]>([]); const [sessionRecords, setSessionRecords] = useState<LoanRecord[]>([]); const [employees, setEmployees] = useState<HrOption[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState("")
  const [open, setOpen] = useState(false); const [values, setValues] = useState<LoanFormValues>(DEFAULT_VALUES); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [target, setTarget] = useState<LoanRecord | null>(null); const [statusValues, setStatusValues] = useState<LoanStatusValues>({ status: "APPROVED" }); const [statusError, setStatusError] = useState("")
  const load = useCallback(async () => { if (!organizationId) { setLoading(false); return } setLoading(true); try { const [report, lookups] = await Promise.all([getReport(context(), "loans", { page: 1, limit: 100 }), loadLookupOptions(context(), ["employees"])]); const reported = report.items.map((item, index) => ({ ...item, id: `report-${String(item.loanNumber ?? index)}-${String(item.employeeId ?? index)}` })) as LoanRecord[]; const freshNumbers = new Set(sessionRecords.map((item) => item.loanNumber)); setRecords([...sessionRecords, ...reported.filter((item) => !freshNumbers.has(item.loanNumber))]); setEmployees(lookups.employees.map((item) => ({ value: item.id, label: `${item.employeeCode ?? ""} · ${item.employeeName ?? item.id}` }))) } catch (caught) { handleError(caught, "Unable to load loans.") } finally { setLoading(false) } }, [context, handleError, organizationId, sessionRecords])
  useEffect(() => { const pending = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(pending) }, [load, refreshVersion])
  const submit = async () => { if (!values.employeeId || !values.loanNumber.trim() || !values.startDate || values.principal <= 0 || values.installmentAmount <= 0) { setError("Employee, loan number, positive amounts, and start date are required."); return } setSubmitting(true); setError(""); try { const saved = await createLoan(context(), { ...values, loanNumber: values.loanNumber.trim(), remarks: values.remarks.trim() || undefined }); setSessionRecords((current) => [saved, ...current]); toast.success("Loan created successfully."); setOpen(false); setValues(DEFAULT_VALUES) } catch (caught) { setError(handleError(caught, "Unable to create the loan.", false)) } finally { setSubmitting(false) } }
  const updateStatus = async () => { if (!target) return; setSubmitting(true); setStatusError(""); try { const saved = await updateLoanStatus(context(), target.id, { status: statusValues.status, rowVersion: target.rowVersion ?? 1 }); setSessionRecords((current) => current.map((item) => item.id === saved.id ? saved : item)); toast.success("Loan status updated."); setTarget(null) } catch (caught) { setStatusError(handleError(caught, "Unable to update the loan.", false)) } finally { setSubmitting(false) } }
  const active = useMemo(() => records.filter((item) => !["SETTLED", "CANCELLED"].includes(item.status)), [records]); const closed = useMemo(() => records.filter((item) => ["SETTLED", "CANCELLED"].includes(item.status)), [records])
  return <HrWorkspaceLayout><HrPageHeader title="Loan Management" description="Create employee loans, monitor outstanding balances, and control payroll-deduction status." badges={[{ label: `${records.length} total`, variant: "secondary" }, { label: `${active.length} open` }, { label: `${closed.length} closed` }]} onRefresh={triggerRefresh} onCreate={() => { setValues(DEFAULT_VALUES); setError(""); setOpen(true) }} createLabel="New loan" /><ActiveLoansSection data={active} loading={loading} search={search} employees={employees} onSearchChange={setSearch} onStatus={(record) => { setTarget(record); setStatusValues({ status: record.status }); setStatusError("") }} /><DeletedLoansSection data={closed} /><LoanFormDialog open={open} values={values} employees={employees} submitting={submitting} error={error} onOpenChange={setOpen} onChange={(name, value) => setValues((current) => ({ ...current, [name]: value }))} onSubmit={submit} /><LoanStatusDialog open={Boolean(target)} values={statusValues} submitting={submitting} error={statusError} onOpenChange={(next) => { if (!next) setTarget(null) }} onChange={(name, value) => setStatusValues((current) => ({ ...current, [name]: value }))} onSubmit={updateStatus} /></HrWorkspaceLayout>
}
